[build]
  # Build command for the React frontend
  command = "cd frontend/react_app && npm install && npm run build"
  
  # Directory to publish (React build output)
  publish = "frontend/react_app/build"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for backend calls (if backend is hosted separately)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/:splat"
  status = 200
  force = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
