[build]
  base = "frontend/react_app"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
