[variables]
NODE_VERSION = "18"
NPM_VERSION = "9"
PYTHON_VERSION = "3.13"

[phases.setup]
nixPkgs = ["python313", "nodejs-18_x", "gcc", "g++", "pkgconfig", "freetype", "fontconfig", "harfbuzz"]

[phases.install]
cmds = [
  "python -m venv venv",
  "./venv/bin/pip install --upgrade pip setuptools wheel",
  "./venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "./venv/bin/uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
