[variables]
WORKDIR = "backend"

[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd backend && python -c 'import sys; print(sys.path)'", "cd backend && python -m pip install --user --upgrade pip", "cd backend && python -m pip install --user -r requirements.txt"]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
